#' NormalControls450k.
#'
#' Normal controls (n = 5) used for copynumber calling by the \code{conumee} package.
#' Data were obtained from NCBI's GEO database, and preprocessed using \code{minfi}.
#'
#' Note: Normal controls for EPIC data are derived from the same samples.
#'
#'
#' @format An object of class \code{MethylSet} as generated with the \code{minfi}
#'   package. Preprocessed with function \code{minfi::preprocessIllumina()}.
#' @source \url{https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE86833}
"NormalControls450k"


#' NormalControlsEpic.
#'
#' Normal controls (n = 5) used for copynumber calling by the \code{conumee} package.
#' Data were obtained from NCBI's GEO database, and preprocessed using \code{minfi}.
#'
#' Note: Normal controls for 450K data are derived from the same samples.
#'
#'
#' @format An object of class \code{MethylSet} as generated with the \code{minfi}
#'   package. Preprocessed with function \code{minfi::preprocessIllumina()}.
#' @source \url{https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE86833}
"NormalControlsEpic"


#' ConumeeAnno450k.
#'
#' Precomputed annotation for the 450K platform used in CNV calling by \code{conumee}.
#'
#' @format An object of class \code{CNV annotation object} as generated by \code{conumee}.
#' Refer to \url{http://bioconductor.org/packages/release/bioc/vignettes/conumee/inst/doc/conumee.html}
#' for more information.
"ConumeeAnno450k"


#' ConumeeAnnoEpic.
#'
#' Precomputed annotation for the EPIC platform used in CNV calling by \code{conumee}.
#'
#' @format An object of class \code{CNV annotation object} as generated by \code{conumee}.
#' Refer to \url{http://bioconductor.org/packages/release/bioc/vignettes/conumee/inst/doc/conumee.html}
#' for more information.
"ConumeeAnnoEpic"


#' RFpurify_ABSOLUTE.
#'
#' Classifier for methylation-based tumor purity prediction trained on ESTIMATE data.
#'
#' @format An object of class \code{randomForest}.
#' @source \url{https://github.com/mwsill/RFpurify}
"RFpurify_ABSOLUTE"


#' RFpurify_ESTIMATE.
#'
#' Classifier for methylation-based tumor purity prediction trained on ESTIMATE data.
#'
#' @format An object of class \code{randomForest}.
#' @source \url{https://github.com/mwsill/RFpurify}
"RFpurify_ESTIMATE"
